upstream django_backend {
    server backend:8000;  # docker-compose servis nomi: backend
}

server {
    listen 80;
    server_name exapmle.com;

    client_max_body_size 50M;


    location / {
        proxy_pass http://django_backend;
        
        # Standart headerlar
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        
        # --- QO'SHILDI: Real IP va HTTPS ni aniqlash uchun ---
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        # -----------------------------------------------------
        
        proxy_redirect off;
    }

    # 2. Statik fayllar
    location /static/ {
        alias /app/static/;
        # --- QO'SHILDI: CSS/JS turlarini to'g'ri aniqlash ---
        include /etc/nginx/mime.types;
        # --- QO'SHILDI: Tezlik uchun (Cache) ---
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # 3. Media fayllar
    location /media/ {
        alias /app/media/;
        include /etc/nginx/mime.types;
        expires 7d;
    }
}

server {
    listen 80;

    server_name i37.uz www.i37.uz;

    return 404; 

}